package com.smallintro.springboot.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("This model is for defect information")
@Entity
@Table(name = "t_defect")
public class DefectInfo {

	@ApiModelProperty(notes = "Autogenerated unique Identity", position = 1)
	@Id
	@GeneratedValue
	@Column(name = "DEFECT_ID")
	private int defectId;

	@Column(name = "DEFECT_DESC", length = 500, nullable = false)
	@Size(min = 50, max = 500, message = "Defect description must be between 50 and 500 characters")
	private String defectDesc;
	@Column(name = "FEATURE", nullable = false)
	@NotEmpty(message = "Feature can not be empty")
	private String feature;
	@Column(name = "DEFECT_DATE")
	private Date defectDate;
	@Column(name = "SOLUTION_DATE")
	private Date solutionDate;
	@Column(name = "TESTER_NAME", nullable = false)
	@NotEmpty(message = "Tester name can not be empty")
	private String testerName;
	@Column(name = "DEVELOPER_NAME", nullable = false)
	private String developerName;
	@Column(name = "DEFECT_STATUS", nullable = false)
	@NotEmpty(message = "Defect status can not be empty")
	private String defectStatus;
	@Column(name = "DEV_REMARK", length = 100)
	private String devRemark;

	@Column(name = "TEST_REMARK", length = 100)
	@Size(min = 10, message = "Tester remark should be at least 20 character")
	private String testRemark;

	public int getDefectId() {
		return defectId;
	}

	public void setDefectId(int defectId) {
		this.defectId = defectId;
	}

	public String getDefectDesc() {
		return defectDesc;
	}

	public void setDefectDesc(String defectDesc) {
		this.defectDesc = defectDesc;
	}

	public String getFeature() {
		return feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	public Date getDefectDate() {
		return defectDate;
	}

	public void setDefectDate(Date defectDate) {
		this.defectDate = defectDate;
	}

	public Date getSolutionDate() {
		return solutionDate;
	}

	public void setSolutionDate(Date solutionDate) {
		this.solutionDate = solutionDate;
	}

	public String getTesterName() {
		return testerName;
	}

	public void setTesterName(String testerName) {
		this.testerName = testerName;
	}

	public String getDeveloperName() {
		return developerName;
	}

	public void setDeveloperName(String developerName) {
		this.developerName = developerName;
	}

	public String getDefectStatus() {
		return defectStatus;
	}

	public void setDefectStatus(String defectStatus) {
		this.defectStatus = defectStatus;
	}

	public String getDevRemark() {
		return devRemark;
	}

	public void setDevRemark(String devRemark) {
		this.devRemark = devRemark;
	}

	public String getTestRemark() {
		return testRemark;
	}

	public void setTestRemark(String testRemark) {
		this.testRemark = testRemark;
	}

	@Override
	public String toString() {
		return "DefectInfo [defectId=" + defectId + ", defectDesc=" + defectDesc + ", feature=" + feature
				+ ", defectDate=" + defectDate + ", solutionDate=" + solutionDate + ", testerName=" + testerName
				+ ", developerName=" + developerName + ", defectStatus=" + defectStatus + ", devRemark=" + devRemark
				+ ", testRemark=" + testRemark + "]";
	}

}
